AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SlackWebhookURL:
    Type: String
    Description: "Enter the Slack Webhook URL as the input event to the Lambda function in JSON format {\"SlackWebhookURL\":\"<Replace with Slack Webhook URL you created earlier>\"}"
    Default: ""

Globals:
  Function:
    Runtime: python3.11
    Architectures:
      - "arm64"

Resources:

  ExposedKeyStepFunction:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state_machine/exposed_access_keys.asl.json
      DefinitionSubstitutions:
        LookupCloudTrailEvents: !GetAtt LookupCloudTrailEvents.Arn
        NotifySecurity: !GetAtt NotifySecurity.Arn
      Events:
        CloudWatchEvent:
          Type: CloudWatchEvent
          Properties: 
            Pattern:
              source: 
                - "aws.trustedadvisor"
              detail-type: 
                - "Trusted Advisor Check Item Refresh Notification"
              detail: 
                status: 
                  - "ERROR"
                check-name:
                  - "Exposed Access Keys"
            State: "ENABLED"
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "iam:DeleteAccessKey"
              Resource: "*"
        - LambdaInvokePolicy:
            FunctionName: !Ref LookupCloudTrailEvents
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifySecurity
 
  LookupCloudTrailEvents:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda_functions/
      Handler: lookup_cloudtrail_events.lambda_handler
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "cloudtrail:LookupEvents"
              Resource: "*"
 
  NotifySecurity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda_functions/
      Handler: notify_security.lambda_handler
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName
      Environment:
        Variables: 
          TOPIC_ARN: !Ref NotificationTopic
          SlackWebhook_URL: !Ref SlackWebhookURL

  NotificationTopic:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: "SecurityNotificationTopic"